[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**"]
  external_node_modules = ["mongodb"]

[build.environment]
  # Настройка переменных окружения для функций
  AWS_LAMBDA_JS_RUNTIME = "nodejs20.x"
  NODE_VERSION = "20"
  # Добавляем режим отладки
  DEBUG = "netlify:function:invoke,netlify:edge"

# Разрешаем CORS для всех доменов с конкретными заголовками
[[headers]]
  for = "/api/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Cache-Control = "no-store, no-cache"
    
# Детальные заголовки для функций
[[headers]]
  for = "/.netlify/functions/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Cache-Control = "no-store, no-cache"

# Отключаем кеширование для всего сайта
[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "no-store, must-revalidate"
    Pragma = "no-cache"

# API-редиректы с четким указанием для обоих доменов
[[redirects]]
  from = "/api/blog/*"
  to = "/.netlify/functions/blog/:splat"
  status = 200
  force = true
  
[[redirects]]
  from = "/api/blog"
  to = "/.netlify/functions/blog"
  status = 200
  force = true

# Редирект для ошибки 404
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
