[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

# Редирект HTTP → HTTPS
[[redirects]]
  from = "http://neurogenlab.de/*"
  to = "https://neurogenlab.de/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.neurogenlab.de/*"
  to = "https://neurogenlab.de/:splat"
  status = 301
  force = true

# Редирект WWW → без WWW
[[redirects]]
  from = "https://www.neurogenlab.de/*"
  to = "https://neurogenlab.de/:splat"
  status = 301
  force = true

# API-редиректы (оставляем как есть)
[[redirects]]
  from = "/api/posts"
  to = "/.netlify/functions/blog"
  status = 200
  force = true
  methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]

[[redirects]]
  from = "/api/posts/*"
  to = "/.netlify/functions/blog/:splat"
  status = 200
  force = true
  methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]

# Основной редирект для Next.js SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
