[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

# API-редиректы
[[redirects]]
  from = "/api/*"
  to = "https://neurogenlab.de/api/:splat"
  status = 200
  force = true

  [functions]
  included_files = ["**/*.js", "**/*.ts"]
  node_bundler = "esbuild"


# Основной редирект для Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
