[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

# API-редиректы
[[redirects]]
  from = "/api/posts"
  to = "/.netlify/functions/blog"
  status = 200
  force = true
  methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]

[[redirects]]
  from = "/api/posts/*"
  to = "/.netlify/functions/blog/:splat"
  status = 200
  force = true
  methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]

# Основной редирект для Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
