[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[build.environment]
  # Настройка переменных окружения для функций
  AWS_LAMBDA_JS_RUNTIME = "nodejs20.x"
  NODE_VERSION = "20"

# Разрешаем CORS для всех доменов
[[headers]]
  for = "/api/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    
# Детальные заголовки для функций
[[headers]]
  for = "/.netlify/functions/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

# API-редиректы с четким указанием для обоих доменов
[[redirects]]
  from = "/api/blog/*"
  to = "/.netlify/functions/blog/:splat"
  status = 200
  force = true
  
[[redirects]]
  from = "/api/blog"
  to = "/.netlify/functions/blog"
  status = 200
  force = true

# Основной редирект для Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
