[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[build.environment]
  # Настройка переменных окружения для функций
  AWS_LAMBDA_JS_RUNTIME = "nodejs16.x"
  NODE_VERSION = "16"

# API-редиректы
[[redirects]]
  from = "/api/blog/*"
  to = "/.netlify/functions/blog/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/blog"
  to = "/.netlify/functions/blog"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Основной редирект для Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
